// Rantoglou-Melas Spyridon 	AM=2342
//Papakostas Kostantinos        AM=2399

enum tokens{
	EQUALS,PLUS,MULTIPLY,DIVIDE,MINUS,LESS_THAN,GREATER_THAN
	,SEMI_COL,COMMA,OPEN_PAR,CLOSE_PAR,OPEN_BRAC,CLOSE_BRAC,AND,OR,NOT,IN,DECLARE,ENDDECLARE
	, IF, ELSE, DO, WHILE, FORCASE, INCASE, WHEN, PRINT, RETURN, CALL, FUNCTION, LESS_EQ, GREATER_EQ, ID, NUMERIC,EXIT,
	PROCEDURE,INOUT,PROGRAM,COPY,OSQUARE_BRAC,CSQUARE_BRAC,DECL_EQUALS,DIFFERENT
};

enum states{
		state0,state1,state2,state3
		,state4,state5,state6,OK,ERROR
};
